omfs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^records/', include('records.urls')),
    url(r'^', include('records.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.conf.urls import url
from . import views

app_name = 'records'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'add/$', views.PatientCreate.as_view(), name='patient-add'),
    url(r'(?P<pk>[0-9]+)/update/$', views.PatientUpdate.as_view(), name='patient-update'),
    url(r'(?P<pk>[0-9]+)/delete/$', views.PatientDelete.as_view(), name='patient-delete'),
]

records/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Patient(models.Model):
    name = models.CharField(max_length=200)
    pid = models.IntegerField(max_length=15)
    date_of_birth = models.DateField()
    medical_history = models.TextField()
    presentation_date = models.DateField()
    presentation = models.TextField()

    def get_absolute_url(self):
        return reverse('records:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Visit(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    visit_date = models.DateField()
    visit_note = models.TextField()
    visit_image = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.visit_date)

records/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Patient, Visit


class PatientForm(forms.ModelForm):

    class Meta:
        model = Patient
        fields = ['name', 'pid', 'date_of_birth', 'medical_history', 'presentation_date', 'presentation']


class VisitForm(forms.ModelForm):

    class Meta:
        model = Visit
        fields = ['visit_date', 'visit_note']

records/views.py
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Patient

class IndexView(generic.ListView):
    template_name = 'records/index.html'
    context_object_name = 'all_patients'

    def get_queryset(self):
        return Patient.objects.all()

class DetailView(generic.DetailView):
    model = Patient
    template_name = 'records/detail.html'

class PatientCreate(CreateView):
    model = Patient
    fields = ['name', 'pid', 'date_of_birth', 'medical_history', 'presentation_date', 'presentation']

class PatientUpdate(UpdateView):
    model = Patient
    fields = ['name', 'pid', 'date_of_birth', 'medical_history', 'presentation_date', 'presentation']

class PatientDelete(DeleteView):
    model = Patient
    success_url = reverse_lazy('records:index')

records/templates/records/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}OMFS Case Record Platform{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'records/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'records:index' %}">OMFS Case Records</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'records:patient-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; New Case
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-right" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

records/templates/records/detail.html
{% extends 'records/base.html' %}
{% block title %}{{ patient }}{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Patient Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>{{ patient.name }} <small>{{ patient.pid }}</small></h3>
                    <h4>{{ patient.date_of_birth }}</h4>
                </div>

                <!-- Delete -->
                <form action="{% url 'records:patient-delete' patient.id  %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="patient_id" value="{{ patient.id }}"/>
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>

                <!-- Edit -->
                <button type="submit" class="btn btn-default btn-sm">
                    <a href="{% url 'records:patient-update' patient.id %}">
                        <span class="glyphicon glyphicon-pencil" style="color:black" aria-hidden="true"></span>
                    </a>
                </button>

            </div>
        </div>

        <!-- Right Patient Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="#">Add New Visit</a></li>
                <li role="presentation"><a href="#">View All</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <p>Medical History: {{patient.medical_history }}</p>
                    <p><strong>{{ patient.presentation_date }}:</strong> {{ patient.presentation }}</p>
                    {% for visit in patient.visit_set.all %}
                        <p><strong>{{ visit.visit_date }}:</strong> {{ visit.visit_note }}</p>
                        <div class="row">
                            {% for image in visit.image_set.all %}
                                <div class="col-sm-3">
                                    <img src="{{ image.image.url }}" class="img-responsive">
                                    <br />
                                </div>
                            {% endfor %}
                        </div>
                        <br />
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

records/templates/records/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

records/templates/records/index.html
{% extends 'records/base.html' %}

{% block body %}
    {% if all_patients %}
        <div class="col-sm-12">
            <h3>OMFS Case Record Platform</h3>
        </div>
        <ul>
            {% for patient in all_patients %}
            <div class="col-sm-8">
                <div class="caption">
                    <h3><a href="{% url 'records:detail' patient.id %}">{{ patient.name }}</a>&nbsp; <small>{{ patient.pid }}</small></h3>
                    <p>{{ patient.presentation_date }}</p>
                    <p>{{ patient.presentation|truncatechars:200 }}</p>
                    <br>
                </div>
            </div>
            {% endfor %}
        </ul>
    {% else %}
        <h3>You don't have any Patient Records.</h3>
    {% endif %}
{% endblock %}

records/templates/records/patient_form.html
{% extends 'records/base.html' %}

{% block title %}Add a New Patient{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post">
                        {% csrf_token %}
                        {% include 'records/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>

                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

records/templates/records/visit_add.html
{% extends 'records/base.html' %}

{% block title %}Add a New Visit{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post">
                        {% csrf_token %}
                        {% include 'records/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>

                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}